// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: node/proto/node.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_node_proto_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_node_proto_rawDescGZIP(), []int{0}
}

type UUIDInbound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	InboundTag    string                 `protobuf:"bytes,2,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUIDInbound) Reset() {
	*x = UUIDInbound{}
	mi := &file_node_proto_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUIDInbound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUIDInbound) ProtoMessage() {}

func (x *UUIDInbound) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUIDInbound.ProtoReflect.Descriptor instead.
func (*UUIDInbound) Descriptor() ([]byte, []int) {
	return file_node_proto_node_proto_rawDescGZIP(), []int{1}
}

func (x *UUIDInbound) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UUIDInbound) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	UuidInbounds  []*UUIDInbound         `protobuf:"bytes,2,rep,name=uuid_inbounds,json=uuidInbounds,proto3" json:"uuid_inbounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_node_proto_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_node_proto_node_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetUuidInbounds() []*UUIDInbound {
	if x != nil {
		return x.UuidInbounds
	}
	return nil
}

type GetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResponse) Reset() {
	*x = GetUsersResponse{}
	mi := &file_node_proto_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResponse) ProtoMessage() {}

func (x *GetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResponse.ProtoReflect.Descriptor instead.
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_node_proto_rawDescGZIP(), []int{3}
}

func (x *GetUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_node_proto_node_proto protoreflect.FileDescriptor

const file_node_proto_node_proto_rawDesc = "" +
	"\n" +
	"\x15node/proto/node.proto\x12\x04node\"\x11\n" +
	"\x0fGetUsersRequest\"B\n" +
	"\vUUIDInbound\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1f\n" +
	"\vinbound_tag\x18\x02 \x01(\tR\n" +
	"inboundTag\"Z\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x126\n" +
	"\ruuid_inbounds\x18\x02 \x03(\v2\x11.node.UUIDInboundR\fuuidInbounds\"4\n" +
	"\x10GetUsersResponse\x12 \n" +
	"\x05users\x18\x01 \x03(\v2\n" +
	".node.UserR\x05users2J\n" +
	"\vNodeService\x12;\n" +
	"\bGetUsers\x12\x15.node.GetUsersRequest\x1a\x16.node.GetUsersResponse\"\x00B\tZ\a./protob\x06proto3"

var (
	file_node_proto_node_proto_rawDescOnce sync.Once
	file_node_proto_node_proto_rawDescData []byte
)

func file_node_proto_node_proto_rawDescGZIP() []byte {
	file_node_proto_node_proto_rawDescOnce.Do(func() {
		file_node_proto_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_node_proto_rawDesc), len(file_node_proto_node_proto_rawDesc)))
	})
	return file_node_proto_node_proto_rawDescData
}

var file_node_proto_node_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_node_proto_node_proto_goTypes = []any{
	(*GetUsersRequest)(nil),  // 0: node.GetUsersRequest
	(*UUIDInbound)(nil),      // 1: node.UUIDInbound
	(*User)(nil),             // 2: node.User
	(*GetUsersResponse)(nil), // 3: node.GetUsersResponse
}
var file_node_proto_node_proto_depIdxs = []int32{
	1, // 0: node.User.uuid_inbounds:type_name -> node.UUIDInbound
	2, // 1: node.GetUsersResponse.users:type_name -> node.User
	0, // 2: node.NodeService.GetUsers:input_type -> node.GetUsersRequest
	3, // 3: node.NodeService.GetUsers:output_type -> node.GetUsersResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_node_proto_node_proto_init() }
func file_node_proto_node_proto_init() {
	if File_node_proto_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_node_proto_rawDesc), len(file_node_proto_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_proto_node_proto_goTypes,
		DependencyIndexes: file_node_proto_node_proto_depIdxs,
		MessageInfos:      file_node_proto_node_proto_msgTypes,
	}.Build()
	File_node_proto_node_proto = out.File
	file_node_proto_node_proto_goTypes = nil
	file_node_proto_node_proto_depIdxs = nil
}
