// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: node.proto

package proto

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListUsersRequest is an empty request for listing users.
type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

// IdInbound represents an ID and inbound tag pair for a user.
type IdInbound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InboundTag    string                 `protobuf:"bytes,2,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdInbound) Reset() {
	*x = IdInbound{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdInbound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdInbound) ProtoMessage() {}

func (x *IdInbound) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdInbound.ProtoReflect.Descriptor instead.
func (*IdInbound) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *IdInbound) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IdInbound) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

// User represents a user on the node.
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	IdInbounds    []*IdInbound           `protobuf:"bytes,2,rep,name=id_inbounds,json=idInbounds,proto3" json:"id_inbounds,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetIdInbounds() []*IdInbound {
	if x != nil {
		return x.IdInbounds
	}
	return nil
}

func (x *User) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// ListUsersResponse contains a list of users.
type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{3}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

// GetApiStatsRequest is an empty request for retrieving API statistics.
type GetApiStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiStatsRequest) Reset() {
	*x = GetApiStatsRequest{}
	mi := &file_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiStatsRequest) ProtoMessage() {}

func (x *GetApiStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiStatsRequest.ProtoReflect.Descriptor instead.
func (*GetApiStatsRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{4}
}

// Stat represents a single statistic entry.
type Stat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stat) Reset() {
	*x = Stat{}
	mi := &file_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stat) ProtoMessage() {}

func (x *Stat) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stat.ProtoReflect.Descriptor instead.
func (*Stat) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{5}
}

func (x *Stat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stat) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// GetApiStatsResponse contains API statistics.
type GetApiStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*Stat                `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiStatsResponse) Reset() {
	*x = GetApiStatsResponse{}
	mi := &file_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiStatsResponse) ProtoMessage() {}

func (x *GetApiStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiStatsResponse.ProtoReflect.Descriptor instead.
func (*GetApiStatsResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{6}
}

func (x *GetApiStatsResponse) GetStats() []*Stat {
	if x != nil {
		return x.Stats
	}
	return nil
}

// GetLogDataRequest is an empty request for retrieving log data.
type GetLogDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogDataRequest) Reset() {
	*x = GetLogDataRequest{}
	mi := &file_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogDataRequest) ProtoMessage() {}

func (x *GetLogDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogDataRequest.ProtoReflect.Descriptor instead.
func (*GetLogDataRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{7}
}

// UserLogData contains log data for a specific user.
type UserLogData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ValidIps      []string               `protobuf:"bytes,1,rep,name=valid_ips,json=validIps,proto3" json:"valid_ips,omitempty"`
	DnsStats      map[string]int32       `protobuf:"bytes,2,rep,name=dns_stats,json=dnsStats,proto3" json:"dns_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLogData) Reset() {
	*x = UserLogData{}
	mi := &file_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLogData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogData) ProtoMessage() {}

func (x *UserLogData) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogData.ProtoReflect.Descriptor instead.
func (*UserLogData) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{8}
}

func (x *UserLogData) GetValidIps() []string {
	if x != nil {
		return x.ValidIps
	}
	return nil
}

func (x *UserLogData) GetDnsStats() map[string]int32 {
	if x != nil {
		return x.DnsStats
	}
	return nil
}

// GetLogDataResponse contains log data for multiple users.
type GetLogDataResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	UserLogData   map[string]*UserLogData `protobuf:"bytes,1,rep,name=user_log_data,json=userLogData,proto3" json:"user_log_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogDataResponse) Reset() {
	*x = GetLogDataResponse{}
	mi := &file_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogDataResponse) ProtoMessage() {}

func (x *GetLogDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogDataResponse.ProtoReflect.Descriptor instead.
func (*GetLogDataResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{9}
}

func (x *GetLogDataResponse) GetUserLogData() map[string]*UserLogData {
	if x != nil {
		return x.UserLogData
	}
	return nil
}

// AddUserRequest specifies a user to add to the node.
type AddUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	InboundTag    string                 `protobuf:"bytes,2,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRequest) Reset() {
	*x = AddUserRequest{}
	mi := &file_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRequest) ProtoMessage() {}

func (x *AddUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRequest.ProtoReflect.Descriptor instead.
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{10}
}

func (x *AddUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AddUserRequest) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

// AddUserResponse contains the generated credential for the new user.
type AddUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    string                 `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	Status        *status.Status         `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserResponse) Reset() {
	*x = AddUserResponse{}
	mi := &file_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserResponse) ProtoMessage() {}

func (x *AddUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserResponse.ProtoReflect.Descriptor instead.
func (*AddUserResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{11}
}

func (x *AddUserResponse) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

func (x *AddUserResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// DeleteUserRequest specifies a user to delete from the node.
type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	InboundTag    string                 `protobuf:"bytes,2,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DeleteUserRequest) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

// OperationResponse represents the result of an operation.
type OperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *status.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{13}
}

func (x *OperationResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// SetUserEnabledRequest specifies a user to enable or disable.
type SetUserEnabledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserEnabledRequest) Reset() {
	*x = SetUserEnabledRequest{}
	mi := &file_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserEnabledRequest) ProtoMessage() {}

func (x *SetUserEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserEnabledRequest.ProtoReflect.Descriptor instead.
func (*SetUserEnabledRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{14}
}

func (x *SetUserEnabledRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SetUserEnabledRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12\x04node\x1a\x17google/rpc/status.proto\"\x12\n" +
	"\x10ListUsersRequest\"<\n" +
	"\tIdInbound\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vinbound_tag\x18\x02 \x01(\tR\n" +
	"inboundTag\"n\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x120\n" +
	"\vid_inbounds\x18\x02 \x03(\v2\x0f.node.IdInboundR\n" +
	"idInbounds\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\"5\n" +
	"\x11ListUsersResponse\x12 \n" +
	"\x05users\x18\x01 \x03(\v2\n" +
	".node.UserR\x05users\"\x14\n" +
	"\x12GetApiStatsRequest\"0\n" +
	"\x04Stat\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"7\n" +
	"\x13GetApiStatsResponse\x12 \n" +
	"\x05stats\x18\x01 \x03(\v2\n" +
	".node.StatR\x05stats\"\x13\n" +
	"\x11GetLogDataRequest\"\xa5\x01\n" +
	"\vUserLogData\x12\x1b\n" +
	"\tvalid_ips\x18\x01 \x03(\tR\bvalidIps\x12<\n" +
	"\tdns_stats\x18\x02 \x03(\v2\x1f.node.UserLogData.DnsStatsEntryR\bdnsStats\x1a;\n" +
	"\rDnsStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xb6\x01\n" +
	"\x12GetLogDataResponse\x12M\n" +
	"\ruser_log_data\x18\x01 \x03(\v2).node.GetLogDataResponse.UserLogDataEntryR\vuserLogData\x1aQ\n" +
	"\x10UserLogDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.node.UserLogDataR\x05value:\x028\x01\"M\n" +
	"\x0eAddUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1f\n" +
	"\vinbound_tag\x18\x02 \x01(\tR\n" +
	"inboundTag\"]\n" +
	"\x0fAddUserResponse\x12\x1e\n" +
	"\n" +
	"credential\x18\x01 \x01(\tR\n" +
	"credential\x12*\n" +
	"\x06status\x18\x02 \x01(\v2\x12.google.rpc.StatusR\x06status\"P\n" +
	"\x11DeleteUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1f\n" +
	"\vinbound_tag\x18\x02 \x01(\tR\n" +
	"inboundTag\"?\n" +
	"\x11OperationResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06status\"M\n" +
	"\x15SetUserEnabledRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled2\x9c\x03\n" +
	"\vNodeService\x12>\n" +
	"\tListUsers\x12\x16.node.ListUsersRequest\x1a\x17.node.ListUsersResponse\"\x00\x12D\n" +
	"\vGetApiStats\x12\x18.node.GetApiStatsRequest\x1a\x19.node.GetApiStatsResponse\"\x00\x12A\n" +
	"\n" +
	"GetLogData\x12\x17.node.GetLogDataRequest\x1a\x18.node.GetLogDataResponse\"\x00\x128\n" +
	"\aAddUser\x12\x14.node.AddUserRequest\x1a\x15.node.AddUserResponse\"\x00\x12@\n" +
	"\n" +
	"DeleteUser\x12\x17.node.DeleteUserRequest\x1a\x17.node.OperationResponse\"\x00\x12H\n" +
	"\x0eSetUserEnabled\x12\x1b.node.SetUserEnabledRequest\x1a\x17.node.OperationResponse\"\x00B\tZ\a./protob\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_node_proto_goTypes = []any{
	(*ListUsersRequest)(nil),      // 0: node.ListUsersRequest
	(*IdInbound)(nil),             // 1: node.IdInbound
	(*User)(nil),                  // 2: node.User
	(*ListUsersResponse)(nil),     // 3: node.ListUsersResponse
	(*GetApiStatsRequest)(nil),    // 4: node.GetApiStatsRequest
	(*Stat)(nil),                  // 5: node.Stat
	(*GetApiStatsResponse)(nil),   // 6: node.GetApiStatsResponse
	(*GetLogDataRequest)(nil),     // 7: node.GetLogDataRequest
	(*UserLogData)(nil),           // 8: node.UserLogData
	(*GetLogDataResponse)(nil),    // 9: node.GetLogDataResponse
	(*AddUserRequest)(nil),        // 10: node.AddUserRequest
	(*AddUserResponse)(nil),       // 11: node.AddUserResponse
	(*DeleteUserRequest)(nil),     // 12: node.DeleteUserRequest
	(*OperationResponse)(nil),     // 13: node.OperationResponse
	(*SetUserEnabledRequest)(nil), // 14: node.SetUserEnabledRequest
	nil,                           // 15: node.UserLogData.DnsStatsEntry
	nil,                           // 16: node.GetLogDataResponse.UserLogDataEntry
	(*status.Status)(nil),         // 17: google.rpc.Status
}
var file_node_proto_depIdxs = []int32{
	1,  // 0: node.User.id_inbounds:type_name -> node.IdInbound
	2,  // 1: node.ListUsersResponse.users:type_name -> node.User
	5,  // 2: node.GetApiStatsResponse.stats:type_name -> node.Stat
	15, // 3: node.UserLogData.dns_stats:type_name -> node.UserLogData.DnsStatsEntry
	16, // 4: node.GetLogDataResponse.user_log_data:type_name -> node.GetLogDataResponse.UserLogDataEntry
	17, // 5: node.AddUserResponse.status:type_name -> google.rpc.Status
	17, // 6: node.OperationResponse.status:type_name -> google.rpc.Status
	8,  // 7: node.GetLogDataResponse.UserLogDataEntry.value:type_name -> node.UserLogData
	0,  // 8: node.NodeService.ListUsers:input_type -> node.ListUsersRequest
	4,  // 9: node.NodeService.GetApiStats:input_type -> node.GetApiStatsRequest
	7,  // 10: node.NodeService.GetLogData:input_type -> node.GetLogDataRequest
	10, // 11: node.NodeService.AddUser:input_type -> node.AddUserRequest
	12, // 12: node.NodeService.DeleteUser:input_type -> node.DeleteUserRequest
	14, // 13: node.NodeService.SetUserEnabled:input_type -> node.SetUserEnabledRequest
	3,  // 14: node.NodeService.ListUsers:output_type -> node.ListUsersResponse
	6,  // 15: node.NodeService.GetApiStats:output_type -> node.GetApiStatsResponse
	9,  // 16: node.NodeService.GetLogData:output_type -> node.GetLogDataResponse
	11, // 17: node.NodeService.AddUser:output_type -> node.AddUserResponse
	13, // 18: node.NodeService.DeleteUser:output_type -> node.OperationResponse
	13, // 19: node.NodeService.SetUserEnabled:output_type -> node.OperationResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
