version: 2

before:
  hooks:
    - go mod tidy

snapshot:
  version_template: "{{ .Tag }}"
checksum:
  name_template: "checksums.txt"

builds:
  - id: amd64
    binary: v2ray-stat
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - GOFLAGS=-mod=mod
    ldflags:
      - -s -w
      - -X main.Version={{ .Tag }}

  - id: arm64
    binary: v2ray-stat
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=0
      - GOFLAGS=-mod=mod
    ldflags:
      - -s -w
      - -X main.Version={{ .Tag }}

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .Env.GITHUB_REPOSITORY_NAME }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
