builds:
  - binary: xcore
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    flags:
      - -mod=vendor

release:
  prerelease: auto

checksum:
  name_template: 'checksums.txt'