version: 2

before:
  hooks:
    - go mod tidy

snapshot:
  version_template: "{{ .Tag }}"
checksum:
  name_template: "checksums.txt"

builds:
  - id: amd64
    binary: xcore
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
      - -X main.Version={{ .Tag }}

  - id: arm64
    binary: xcore
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.Version={{ .Tag }}

archives:
  - id: XCore-go
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - .env
      - LICENSE

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .Env.GITHUB_REPOSITORY_NAME }}"
  name_template: "v{{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"