x-common: &common
  ulimits:
    nofile:
      soft: 1048576
      hard: 1048576
  restart: always
  networks:
    - exodus-network

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: 5

x-env: &env
  env_file: .env

services:
  exodus:
    image: ghcr.io/adam-sizzler/exodus:latest
    container_name: exodus
    hostname: exodus
    <<: [*common, *logging, *env]
    volumes:
      - valkey-socket:/var/run/valkey
      - ./configs/notifications/notifications-config.yml:/opt/app/configs/notifications/notifications-config.yml:ro
    ports:
      - 127.0.0.1:3000:${APP_PORT:-3000}
      - 127.0.0.1:3001:${METRICS_PORT:-3001}
    healthcheck:
      test: ['CMD-SHELL', 'path=$$(echo "$${APP_PATH:-}" | sed "s|/*$$||"); curl -f "http://localhost:$${METRICS_PORT:-3001}$${path}/health"']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      exodus-db:
        condition: service_healthy
      exodus-redis:
        condition: service_healthy

  exodus-db:
    image: postgres:18.4
    container_name: exodus-db
    hostname: exodus-db
    shm_size: 512mb
    <<: [*common, *logging, *env]
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=UTC
    ports:
      - "127.0.0.1:6868:5432"
    volumes:
      - exodus-db-data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 3s
      timeout: 10s
      retries: 3

  exodus-redis:
    image: valkey/valkey:9-alpine
    container_name: exodus-redis
    hostname: exodus-redis
    <<: [*common, *logging]
    volumes:
      - valkey-socket:/var/run/valkey
    command: >
      valkey-server
      --save ""
      --appendonly no
      --maxmemory-policy noeviction
      --loglevel warning
      --unixsocket /var/run/valkey/valkey.sock
      --unixsocketperm 777
      --port 0
    healthcheck:
      test: ['CMD', 'valkey-cli', '-s', '/var/run/valkey/valkey.sock', 'ping']
      interval: 3s
      timeout: 3s
      retries: 3

networks:
  exodus-network:
    name: exodus-network
    driver: bridge
    external: false

volumes:
  exodus-db-data:
    name: exodus-db-data
    driver: local
    external: false
  valkey-socket:
    name: valkey-socket
    driver: local
    external: false
