# v2ray-stat Configuration File
# This file specifies paths and settings for the v2ray-stat monitoring application.

# Log Settings
log:
  loglevel: info                                          # Logging level: none, error, warn, info, debug, trace. NONE disables logging; each level includes messages from lower levels.
  logmode: inclusive                                      # Log mode: inclusive = this and lower levels; exclusive = only this level

# API Settings
api:
  api_token: ""                                           # Token required to access the API endpoints. If empty, access is allowed without authorization. Format: Bearer <token>.
 
# Timezone Settings 
timezone: Asia/Bangkok                                    # IANA timezone name (e.g., Europe/Amsterdam, Asia/Singapore). If empty, uses TZ environment variable or UTC.

# v2ray-stat Settings
v2rs-backend:
  address: 127.0.0.1                                      # IP address of the v2ray-stat API server. 127.0.0.1 means it is accessible only locally (localhost).
  port: 9243                                              # TCP port for v2ray-stat API server. Must be between 1 and 65535.
  monitor:        
    ticker_interval: 10                                   # Interval (in seconds) for polling monitored services and users. Recommended: 5–60.
    online_rate_threshold: 0                              # Minimum rate threshold in kilobits per second (kbps) to consider a user online. 0 means any non-zero rate is considered online.
  nodes:                                                  # List of monitored nodes and their API connection parameters.
    - node_name: swe                                      # Display name of the node.
      address: 127.0.0.1                                  # Node API endpoint address in host format.
      port: 9253                                          # Node API endpoint address in port format.
    - node_name: rus
      address: 1.2.3.4                                    # Node API endpoint address in host format.
      port: 9253                                          # Node API endpoint address in port format.
      mtls:
        cert: /usr/local/etc/v2ray-stat/certs/node.crt
        key: /usr/local/etc/v2ray-stat/certs/node.key
        ca_cert: /usr/local/etc/v2ray-stat/certs/node.crt
    - node_name: nl
      address: example.com                                # Node API endpoint address in host format.
      port: 443                                           # Node API endpoint address in port format.
      mtls:                                               # mTLS (mutual TLS) configuration for secure connection to the node.
        cert: /usr/local/etc/v2ray-stat/certs/node.crt    # Path to the client's TLS certificate.
        key: /usr/local/etc/v2ray-stat/certs/node.key     # Path to the client's private key.
        ca_cert: /usr/local/etc/v2ray-stat/certs/node.crt # Path to the CA certificate for server verification.
  subscription:
    address: 127.0.0.1
    grpc_port: 9263
    # mtls:                                               # mTLS (mutual TLS) configuration for secure connection to the node.
    #   cert: /usr/local/etc/v2ray-stat/certs/node.crt    # Path to the client's TLS certificate.
    #   key: /usr/local/etc/v2ray-stat/certs/node.key     # Path to the client's private key.
    #   ca_cert: /usr/local/etc/v2ray-stat/certs/node.crt # Path to the CA certificate for server verification.

# Paths & Logging 
paths: 
  database: /usr/local/etc/v2ray-stat/data.db             # Path to the SQLite database for tracking user sessions and usage.
 
# Statistics Columns Configuration 
stats_columns: 
  server: 
    sort: rate desc                                       # Sorting rule for server statistics. Format: "<column> <ASC|DESC>". Default: "source ASC". Valid columns: source, rate, uplink, downlink, sess_uplink, sess_downlink.
    columns:                                              # List of columns to display in server statistics. If empty, no server statistics are shown.
      - node_name                                         # Node name where the traffic is measured.
      - source                                            # Source of traffic (e.g., IP or hostname).
      - rate                                              # Current traffic rate in bits per second (bps).
      - uplink                                            # Total uploaded traffic in bytes.
      - downlink                                          # Total downloaded traffic in bytes.
      # - sess_uplink                                     # Session-based uploaded traffic in bytes (reset after reconnect).
      # - sess_downlink                                   # Session-based downloaded traffic in bytes (reset after reconnect).
  client: 
    sort: rate desc                                       # Sorting rule for client statistics. Same format and rules as for server stats.
    columns:                                              # List of columns to display in client statistics. If empty, no client statistics are shown.
      - node_name                                         # Node name where the client is connected.
      - user                                              # Client username or identifier.
      - last_seen                                         # Timestamp of the last client activity.
      - rate                                              # Current traffic rate in bits per second (bps).
      - uplink                                            # Total uploaded traffic in bytes.
      - downlink                                          # Total downloaded traffic in bytes.
      - traffic_cap
      - sess_uplink                                     # Session-based uploaded traffic in bytes (reset after reconnect).
      - sess_downlink                                   # Session-based downloaded traffic in bytes (reset after reconnect).
      - enabled                                         # Whether the client is enabled (true/false).
      - created                                         # Timestamp when the client was created.
      - sub_end                                         # Subscription end date for the client.
      - renew                                           # Renewal status or date for the client.
      - id                                              # Unique client identifier (ID).
      - inbound_tag                                     # Inbound tag associated with the client.
      - lim_ip                                          # IP limit for the client (number of allowed IPs).
      - ips                                             # List of IPs currently used by the client.
