// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: backend.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_backend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{0}
}

type GetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeUsers     []*BackendUsers        `protobuf:"bytes,1,rep,name=node_users,json=nodeUsers,proto3" json:"node_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResponse) Reset() {
	*x = GetUsersResponse{}
	mi := &file_backend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResponse) ProtoMessage() {}

func (x *GetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResponse.ProtoReflect.Descriptor instead.
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{1}
}

func (x *GetUsersResponse) GetNodeUsers() []*BackendUsers {
	if x != nil {
		return x.NodeUsers
	}
	return nil
}

type BackendUsers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port          string                 `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Users         []*User                `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendUsers) Reset() {
	*x = BackendUsers{}
	mi := &file_backend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendUsers) ProtoMessage() {}

func (x *BackendUsers) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendUsers.ProtoReflect.Descriptor instead.
func (*BackendUsers) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{2}
}

func (x *BackendUsers) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *BackendUsers) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BackendUsers) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *BackendUsers) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Inbounds      []*IdEntry             `protobuf:"bytes,2,rep,name=inbounds,proto3" json:"inbounds,omitempty"`
	Rate          string                 `protobuf:"bytes,3,opt,name=rate,proto3" json:"rate,omitempty"`
	Enabled       string                 `protobuf:"bytes,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Created       int64                  `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty"`
	SubEnd        int64                  `protobuf:"varint,6,opt,name=sub_end,json=subEnd,proto3" json:"sub_end,omitempty"`
	Renew         int32                  `protobuf:"varint,7,opt,name=renew,proto3" json:"renew,omitempty"`
	LimIp         int32                  `protobuf:"varint,8,opt,name=lim_ip,json=limIp,proto3" json:"lim_ip,omitempty"`
	Ips           string                 `protobuf:"bytes,9,opt,name=ips,proto3" json:"ips,omitempty"`
	Uplink        int64                  `protobuf:"varint,10,opt,name=uplink,proto3" json:"uplink,omitempty"`
	Downlink      int64                  `protobuf:"varint,11,opt,name=downlink,proto3" json:"downlink,omitempty"`
	TrafficCap    int64                  `protobuf:"varint,12,opt,name=traffic_cap,json=trafficCap,proto3" json:"traffic_cap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_backend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *User) GetInbounds() []*IdEntry {
	if x != nil {
		return x.Inbounds
	}
	return nil
}

func (x *User) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *User) GetEnabled() string {
	if x != nil {
		return x.Enabled
	}
	return ""
}

func (x *User) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *User) GetSubEnd() int64 {
	if x != nil {
		return x.SubEnd
	}
	return 0
}

func (x *User) GetRenew() int32 {
	if x != nil {
		return x.Renew
	}
	return 0
}

func (x *User) GetLimIp() int32 {
	if x != nil {
		return x.LimIp
	}
	return 0
}

func (x *User) GetIps() string {
	if x != nil {
		return x.Ips
	}
	return ""
}

func (x *User) GetUplink() int64 {
	if x != nil {
		return x.Uplink
	}
	return 0
}

func (x *User) GetDownlink() int64 {
	if x != nil {
		return x.Downlink
	}
	return 0
}

func (x *User) GetTrafficCap() int64 {
	if x != nil {
		return x.TrafficCap
	}
	return 0
}

type IdEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InboundTag    string                 `protobuf:"bytes,1,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdEntry) Reset() {
	*x = IdEntry{}
	mi := &file_backend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdEntry) ProtoMessage() {}

func (x *IdEntry) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdEntry.ProtoReflect.Descriptor instead.
func (*IdEntry) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{4}
}

func (x *IdEntry) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

func (x *IdEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_backend_proto protoreflect.FileDescriptor

const file_backend_proto_rawDesc = "" +
	"\n" +
	"\rbackend.proto\x12\fprotoBackend\"\x11\n" +
	"\x0fGetUsersRequest\"M\n" +
	"\x10GetUsersResponse\x129\n" +
	"\n" +
	"node_users\x18\x01 \x03(\v2\x1a.protoBackend.BackendUsersR\tnodeUsers\"\x83\x01\n" +
	"\fBackendUsers\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\x12(\n" +
	"\x05users\x18\x04 \x03(\v2\x12.protoBackend.UserR\x05users\"\xc2\x02\n" +
	"\x04User\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x121\n" +
	"\binbounds\x18\x02 \x03(\v2\x15.protoBackend.IdEntryR\binbounds\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\tR\x04rate\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\tR\aenabled\x12\x18\n" +
	"\acreated\x18\x05 \x01(\x03R\acreated\x12\x17\n" +
	"\asub_end\x18\x06 \x01(\x03R\x06subEnd\x12\x14\n" +
	"\x05renew\x18\a \x01(\x05R\x05renew\x12\x15\n" +
	"\x06lim_ip\x18\b \x01(\x05R\x05limIp\x12\x10\n" +
	"\x03ips\x18\t \x01(\tR\x03ips\x12\x16\n" +
	"\x06uplink\x18\n" +
	" \x01(\x03R\x06uplink\x12\x1a\n" +
	"\bdownlink\x18\v \x01(\x03R\bdownlink\x12\x1f\n" +
	"\vtraffic_cap\x18\f \x01(\x03R\n" +
	"trafficCap\":\n" +
	"\aIdEntry\x12\x1f\n" +
	"\vinbound_tag\x18\x01 \x01(\tR\n" +
	"inboundTag\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id2\x8a\x02\n" +
	"\x0eBackendService\x12R\n" +
	"\vStreamUsers\x12\x1d.protoBackend.GetUsersRequest\x1a\x1e.protoBackend.GetUsersResponse\"\x00(\x010\x01\x12K\n" +
	"\bGetUsers\x12\x1d.protoBackend.GetUsersRequest\x1a\x1e.protoBackend.GetUsersResponse\"\x00\x12W\n" +
	"\x14GetSubscriptionUsers\x12\x1d.protoBackend.GetUsersRequest\x1a\x1e.protoBackend.GetUsersResponse\"\x00B\x1aZ\x18v2ray-stat/backend/protob\x06proto3"

var (
	file_backend_proto_rawDescOnce sync.Once
	file_backend_proto_rawDescData []byte
)

func file_backend_proto_rawDescGZIP() []byte {
	file_backend_proto_rawDescOnce.Do(func() {
		file_backend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_proto_rawDesc), len(file_backend_proto_rawDesc)))
	})
	return file_backend_proto_rawDescData
}

var file_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_backend_proto_goTypes = []any{
	(*GetUsersRequest)(nil),  // 0: protoBackend.GetUsersRequest
	(*GetUsersResponse)(nil), // 1: protoBackend.GetUsersResponse
	(*BackendUsers)(nil),     // 2: protoBackend.BackendUsers
	(*User)(nil),             // 3: protoBackend.User
	(*IdEntry)(nil),          // 4: protoBackend.IdEntry
}
var file_backend_proto_depIdxs = []int32{
	2, // 0: protoBackend.GetUsersResponse.node_users:type_name -> protoBackend.BackendUsers
	3, // 1: protoBackend.BackendUsers.users:type_name -> protoBackend.User
	4, // 2: protoBackend.User.inbounds:type_name -> protoBackend.IdEntry
	0, // 3: protoBackend.BackendService.StreamUsers:input_type -> protoBackend.GetUsersRequest
	0, // 4: protoBackend.BackendService.GetUsers:input_type -> protoBackend.GetUsersRequest
	0, // 5: protoBackend.BackendService.GetSubscriptionUsers:input_type -> protoBackend.GetUsersRequest
	1, // 6: protoBackend.BackendService.StreamUsers:output_type -> protoBackend.GetUsersResponse
	1, // 7: protoBackend.BackendService.GetUsers:output_type -> protoBackend.GetUsersResponse
	1, // 8: protoBackend.BackendService.GetSubscriptionUsers:output_type -> protoBackend.GetUsersResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_backend_proto_init() }
func file_backend_proto_init() {
	if File_backend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_proto_rawDesc), len(file_backend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_proto_goTypes,
		DependencyIndexes: file_backend_proto_depIdxs,
		MessageInfos:      file_backend_proto_msgTypes,
	}.Build()
	File_backend_proto = out.File
	file_backend_proto_goTypes = nil
	file_backend_proto_depIdxs = nil
}
