// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: subscription/proto/subscription.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request от сервера (subscription) к клиенту (backend)
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_subscription_proto_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_subscription_proto_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Response от клиента (backend) к серверу (subscription)
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	NodeUsers     []*NodeUsers           `protobuf:"bytes,2,rep,name=node_users,json=nodeUsers,proto3" json:"node_users,omitempty"`
	IsHeartbeat   bool                   `protobuf:"varint,3,opt,name=is_heartbeat,json=isHeartbeat,proto3" json:"is_heartbeat,omitempty"` // Для heartbeat, если true - игнорировать node_users
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_subscription_proto_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_subscription_proto_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Response) GetNodeUsers() []*NodeUsers {
	if x != nil {
		return x.NodeUsers
	}
	return nil
}

func (x *Response) GetIsHeartbeat() bool {
	if x != nil {
		return x.IsHeartbeat
	}
	return false
}

// NodeUsers - структура как в backend/api
type NodeUsers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port          string                 `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Users         []*User                `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeUsers) Reset() {
	*x = NodeUsers{}
	mi := &file_subscription_proto_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeUsers) ProtoMessage() {}

func (x *NodeUsers) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeUsers.ProtoReflect.Descriptor instead.
func (*NodeUsers) Descriptor() ([]byte, []int) {
	return file_subscription_proto_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *NodeUsers) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *NodeUsers) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeUsers) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *NodeUsers) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

// User - структура как в backend/api
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Inbounds      []*IdEntry             `protobuf:"bytes,2,rep,name=inbounds,proto3" json:"inbounds,omitempty"`
	Rate          string                 `protobuf:"bytes,3,opt,name=rate,proto3" json:"rate,omitempty"`
	Enabled       string                 `protobuf:"bytes,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Created       int64                  `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty"`
	SubEnd        int64                  `protobuf:"varint,6,opt,name=sub_end,json=subEnd,proto3" json:"sub_end,omitempty"`
	Renew         int32                  `protobuf:"varint,7,opt,name=renew,proto3" json:"renew,omitempty"`
	LimIp         int32                  `protobuf:"varint,8,opt,name=lim_ip,json=limIp,proto3" json:"lim_ip,omitempty"`
	Ips           string                 `protobuf:"bytes,9,opt,name=ips,proto3" json:"ips,omitempty"`
	Uplink        int64                  `protobuf:"varint,10,opt,name=uplink,proto3" json:"uplink,omitempty"`
	Downlink      int64                  `protobuf:"varint,11,opt,name=downlink,proto3" json:"downlink,omitempty"`
	TrafficCap    int64                  `protobuf:"varint,12,opt,name=traffic_cap,json=trafficCap,proto3" json:"traffic_cap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_subscription_proto_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_subscription_proto_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *User) GetInbounds() []*IdEntry {
	if x != nil {
		return x.Inbounds
	}
	return nil
}

func (x *User) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *User) GetEnabled() string {
	if x != nil {
		return x.Enabled
	}
	return ""
}

func (x *User) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *User) GetSubEnd() int64 {
	if x != nil {
		return x.SubEnd
	}
	return 0
}

func (x *User) GetRenew() int32 {
	if x != nil {
		return x.Renew
	}
	return 0
}

func (x *User) GetLimIp() int32 {
	if x != nil {
		return x.LimIp
	}
	return 0
}

func (x *User) GetIps() string {
	if x != nil {
		return x.Ips
	}
	return ""
}

func (x *User) GetUplink() int64 {
	if x != nil {
		return x.Uplink
	}
	return 0
}

func (x *User) GetDownlink() int64 {
	if x != nil {
		return x.Downlink
	}
	return 0
}

func (x *User) GetTrafficCap() int64 {
	if x != nil {
		return x.TrafficCap
	}
	return 0
}

// IdEntry - структура как в backend/api
type IdEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InboundTag    string                 `protobuf:"bytes,1,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdEntry) Reset() {
	*x = IdEntry{}
	mi := &file_subscription_proto_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdEntry) ProtoMessage() {}

func (x *IdEntry) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdEntry.ProtoReflect.Descriptor instead.
func (*IdEntry) Descriptor() ([]byte, []int) {
	return file_subscription_proto_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *IdEntry) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

func (x *IdEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_subscription_proto_subscription_proto protoreflect.FileDescriptor

const file_subscription_proto_subscription_proto_rawDesc = "" +
	"\n" +
	"%subscription/proto/subscription.proto\x12\x03api\"(\n" +
	"\aRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"{\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12-\n" +
	"\n" +
	"node_users\x18\x02 \x03(\v2\x0e.api.NodeUsersR\tnodeUsers\x12!\n" +
	"\fis_heartbeat\x18\x03 \x01(\bR\visHeartbeat\"n\n" +
	"\tNodeUsers\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\x12\x1f\n" +
	"\x05users\x18\x04 \x03(\v2\t.api.UserR\x05users\"\xb9\x02\n" +
	"\x04User\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12(\n" +
	"\binbounds\x18\x02 \x03(\v2\f.api.IdEntryR\binbounds\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\tR\x04rate\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\tR\aenabled\x12\x18\n" +
	"\acreated\x18\x05 \x01(\x03R\acreated\x12\x17\n" +
	"\asub_end\x18\x06 \x01(\x03R\x06subEnd\x12\x14\n" +
	"\x05renew\x18\a \x01(\x05R\x05renew\x12\x15\n" +
	"\x06lim_ip\x18\b \x01(\x05R\x05limIp\x12\x10\n" +
	"\x03ips\x18\t \x01(\tR\x03ips\x12\x16\n" +
	"\x06uplink\x18\n" +
	" \x01(\x03R\x06uplink\x12\x1a\n" +
	"\bdownlink\x18\v \x01(\x03R\bdownlink\x12\x1f\n" +
	"\vtraffic_cap\x18\f \x01(\x03R\n" +
	"trafficCap\":\n" +
	"\aIdEntry\x12\x1f\n" +
	"\vinbound_tag\x18\x01 \x01(\tR\n" +
	"inboundTag\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id2D\n" +
	"\x13SubscriptionService\x12-\n" +
	"\n" +
	"DataStream\x12\r.api.Response\x1a\f.api.Request(\x010\x01B\x1fZ\x1dv2ray-stat/subscription/protob\x06proto3"

var (
	file_subscription_proto_subscription_proto_rawDescOnce sync.Once
	file_subscription_proto_subscription_proto_rawDescData []byte
)

func file_subscription_proto_subscription_proto_rawDescGZIP() []byte {
	file_subscription_proto_subscription_proto_rawDescOnce.Do(func() {
		file_subscription_proto_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscription_proto_subscription_proto_rawDesc), len(file_subscription_proto_subscription_proto_rawDesc)))
	})
	return file_subscription_proto_subscription_proto_rawDescData
}

var file_subscription_proto_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_subscription_proto_subscription_proto_goTypes = []any{
	(*Request)(nil),   // 0: api.Request
	(*Response)(nil),  // 1: api.Response
	(*NodeUsers)(nil), // 2: api.NodeUsers
	(*User)(nil),      // 3: api.User
	(*IdEntry)(nil),   // 4: api.IdEntry
}
var file_subscription_proto_subscription_proto_depIdxs = []int32{
	2, // 0: api.Response.node_users:type_name -> api.NodeUsers
	3, // 1: api.NodeUsers.users:type_name -> api.User
	4, // 2: api.User.inbounds:type_name -> api.IdEntry
	1, // 3: api.SubscriptionService.DataStream:input_type -> api.Response
	0, // 4: api.SubscriptionService.DataStream:output_type -> api.Request
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_subscription_proto_subscription_proto_init() }
func file_subscription_proto_subscription_proto_init() {
	if File_subscription_proto_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_proto_subscription_proto_rawDesc), len(file_subscription_proto_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscription_proto_subscription_proto_goTypes,
		DependencyIndexes: file_subscription_proto_subscription_proto_depIdxs,
		MessageInfos:      file_subscription_proto_subscription_proto_msgTypes,
	}.Build()
	File_subscription_proto_subscription_proto = out.File
	file_subscription_proto_subscription_proto_goTypes = nil
	file_subscription_proto_subscription_proto_depIdxs = nil
}
