package scopecatalog

// CanonicalResourceOrder defines the canonical ordering of resources.
var CanonicalResourceOrder = []string{
	"config-profiles",
	"snippets",
	"connections",
	"external-squads",
	"hosts",
	"hwid-user-devices",
	"infra-billing",
	"bandwidth-stats",
	"internal-squads",
	"keygen",
	"metadata",
	"node-integrations",
	"node-plugins",
	"nodes",
	"subscription-page-configs",
	"subscription-settings",
	"subscription-template",
	"subscriptions",
	"system",
	"subscription-request-history",
	"users",
}

// StaticEndpoints defines all supported panel endpoints with their scope metadata.
var StaticEndpoints = []EndpointDef{
	{Resource: "config-profiles", Slug: "list-tags", Kind: "read", Method: "GET", Path: "/api/config-profiles/tags", Description: "Get tags of Config Profiles"},
	{Resource: "config-profiles", Slug: "set-tags", Kind: "write", Method: "PATCH", Path: "/api/config-profiles/tags", Description: "Set tags of Config Profile"},
	{Resource: "config-profiles", Slug: "list", Kind: "read", Method: "GET", Path: "/api/config-profiles", Description: "Get config profiles"},
	{Resource: "config-profiles", Slug: "create", Kind: "write", Method: "POST", Path: "/api/config-profiles", Description: "Create config profile"},
	{Resource: "config-profiles", Slug: "update", Kind: "write", Method: "PATCH", Path: "/api/config-profiles", Description: "Update Core Config in specific config profile"},
	{Resource: "config-profiles", Slug: "list-inbounds", Kind: "read", Method: "GET", Path: "/api/config-profiles/inbounds", Description: "Get all inbounds from all config profiles"},
	{Resource: "config-profiles", Slug: "list-profile-inbounds", Kind: "read", Method: "GET", Path: "/api/config-profiles/{uuid}/inbounds", Description: "Get inbounds by profile uuid"},
	{Resource: "config-profiles", Slug: "get", Kind: "read", Method: "GET", Path: "/api/config-profiles/{uuid}", Description: "Get config profile by uuid"},
	{Resource: "config-profiles", Slug: "delete", Kind: "write", Method: "DELETE", Path: "/api/config-profiles/{uuid}", Description: "Delete config profile"},
	{Resource: "config-profiles", Slug: "get-computed", Kind: "read", Method: "GET", Path: "/api/config-profiles/{uuid}/computed-config", Description: "Get computed config profile by uuid"},
	{Resource: "config-profiles", Slug: "reorder", Kind: "write", Method: "POST", Path: "/api/config-profiles/actions/reorder", Description: "Reorder config profiles"},
	{Resource: "snippets", Slug: "list", Kind: "read", Method: "GET", Path: "/api/snippets", Description: "Get snippets"},
	{Resource: "snippets", Slug: "delete", Kind: "write", Method: "DELETE", Path: "/api/snippets", Description: "Delete snippet"},
	{Resource: "snippets", Slug: "create", Kind: "write", Method: "POST", Path: "/api/snippets", Description: "Create snippet"},
	{Resource: "snippets", Slug: "update", Kind: "write", Method: "PATCH", Path: "/api/snippets", Description: "Update snippet"},
	{Resource: "snippets", Slug: "sync", Kind: "write", Method: "POST", Path: "/api/snippets/actions/sync", Description: "Sync snippet to affected config profiles"},
	{Resource: "connections", Slug: "by-user", Kind: "read", Method: "POST", Path: "/api/connections/by-user/{userId}", Description: "Request Connections for User"},
	{Resource: "connections", Slug: "by-user-result", Kind: "read", Method: "GET", Path: "/api/connections/by-user/{jobId}", Description: "Get Connections for User by Job ID"},
	{Resource: "connections", Slug: "drop", Kind: "write", Method: "POST", Path: "/api/connections/drop", Description: "Drop Connections for Users or IPs"},
	{Resource: "connections", Slug: "by-node", Kind: "read", Method: "POST", Path: "/api/connections/by-node/{nodeUuid}", Description: "Request Connections for Node"},
	{Resource: "connections", Slug: "by-node-result", Kind: "read", Method: "GET", Path: "/api/connections/by-node/{jobId}", Description: "Get Connections for Node by Job ID"},
	{Resource: "connections", Slug: "geocheck", Kind: "read", Method: "POST", Path: "/api/connections/geocheck/{nodeUuid}", Description: "Request Geocheck for Node"},
	{Resource: "connections", Slug: "geocheck-result", Kind: "read", Method: "GET", Path: "/api/connections/geocheck/{jobId}", Description: "Get Geocheck for Node by Job ID"},
	{Resource: "external-squads", Slug: "list-tags", Kind: "read", Method: "GET", Path: "/api/external-squads/tags", Description: "Get tags of External Squads"},
	{Resource: "external-squads", Slug: "set-tags", Kind: "write", Method: "PATCH", Path: "/api/external-squads/tags", Description: "Set tags of External Squad"},
	{Resource: "external-squads", Slug: "list", Kind: "read", Method: "GET", Path: "/api/external-squads", Description: "Get all external squads"},
	{Resource: "external-squads", Slug: "create", Kind: "write", Method: "POST", Path: "/api/external-squads", Description: "Create external squad"},
	{Resource: "external-squads", Slug: "update", Kind: "write", Method: "PATCH", Path: "/api/external-squads", Description: "Update external squad"},
	{Resource: "external-squads", Slug: "get", Kind: "read", Method: "GET", Path: "/api/external-squads/{uuid}", Description: "Get external squad by uuid"},
	{Resource: "external-squads", Slug: "delete", Kind: "write", Method: "DELETE", Path: "/api/external-squads/{uuid}", Description: "Delete external squad"},
	{Resource: "external-squads", Slug: "add-users", Kind: "write", Method: "POST", Path: "/api/external-squads/{uuid}/bulk-actions/add-users", Description: "Add all users to external squad"},
	{Resource: "external-squads", Slug: "remove-users", Kind: "write", Method: "DELETE", Path: "/api/external-squads/{uuid}/bulk-actions/remove-users", Description: "Delete users from external squad"},
	{Resource: "external-squads", Slug: "reorder", Kind: "write", Method: "POST", Path: "/api/external-squads/actions/reorder", Description: "Reorder external squads"},
	{Resource: "hosts", Slug: "list-tags", Kind: "read", Method: "GET", Path: "/api/hosts/tags", Description: "Get tags of hosts"},
	{Resource: "hosts", Slug: "create", Kind: "write", Method: "POST", Path: "/api/hosts", Description: "Create a new host"},
	{Resource: "hosts", Slug: "update", Kind: "write", Method: "PATCH", Path: "/api/hosts", Description: "Update a host"},
	{Resource: "hosts", Slug: "list", Kind: "read", Method: "GET", Path: "/api/hosts", Description: "Get hosts"},
	{Resource: "hosts", Slug: "get", Kind: "read", Method: "GET", Path: "/api/hosts/{uuid}", Description: "Get a host by UUID"},
	{Resource: "hosts", Slug: "delete", Kind: "write", Method: "DELETE", Path: "/api/hosts/{uuid}", Description: "Delete a host by UUID"},
	{Resource: "hosts", Slug: "reorder", Kind: "write", Method: "POST", Path: "/api/hosts/actions/reorder", Description: "Reorder hosts"},
	{Resource: "hosts", Slug: "bulk-delete", Kind: "write", Method: "POST", Path: "/api/hosts/bulk/delete", Description: "Delete hosts by UUIDs"},
	{Resource: "hosts", Slug: "bulk-disable", Kind: "write", Method: "POST", Path: "/api/hosts/bulk/disable", Description: "Disable hosts by UUIDs"},
	{Resource: "hosts", Slug: "bulk-enable", Kind: "write", Method: "POST", Path: "/api/hosts/bulk/enable", Description: "Enable hosts by UUIDs"},
	{Resource: "hosts", Slug: "bulk-update", Kind: "write", Method: "PATCH", Path: "/api/hosts/bulk/update", Description: "Update many hosts"},
	{Resource: "hwid-user-devices", Slug: "list", Kind: "read", Method: "GET", Path: "/api/hwid/devices", Description: "Get HWID devices"},
	{Resource: "hwid-user-devices", Slug: "create", Kind: "write", Method: "POST", Path: "/api/hwid/devices", Description: "Create a user HWID device"},
	{Resource: "hwid-user-devices", Slug: "delete", Kind: "write", Method: "POST", Path: "/api/hwid/devices/delete", Description: "Delete a user HWID device"},
	{Resource: "hwid-user-devices", Slug: "delete-all", Kind: "write", Method: "POST", Path: "/api/hwid/devices/delete-all", Description: "Delete all user HWID devices"},
	{Resource: "hwid-user-devices", Slug: "stats", Kind: "read", Method: "GET", Path: "/api/hwid/devices/stats", Description: "Get HWID devices stats"},
	{Resource: "hwid-user-devices", Slug: "top-users", Kind: "read", Method: "GET", Path: "/api/hwid/devices/top-users", Description: "Get top users by HWID devices"},
	{Resource: "hwid-user-devices", Slug: "list-by-user", Kind: "read", Method: "GET", Path: "/api/hwid/devices/{userId}", Description: "Get user HWID devices"},
	{Resource: "infra-billing", Slug: "list-providers", Kind: "read", Method: "GET", Path: "/api/infra-billing/providers", Description: "Get all infra providers"},
	{Resource: "infra-billing", Slug: "create-provider", Kind: "write", Method: "POST", Path: "/api/infra-billing/providers", Description: "Create infra provider"},
	{Resource: "infra-billing", Slug: "update-provider", Kind: "write", Method: "PATCH", Path: "/api/infra-billing/providers", Description: "Update infra provider"},
	{Resource: "infra-billing", Slug: "get-provider", Kind: "read", Method: "GET", Path: "/api/infra-billing/providers/{uuid}", Description: "Get infra provider by uuid"},
	{Resource: "infra-billing", Slug: "delete-provider", Kind: "write", Method: "DELETE", Path: "/api/infra-billing/providers/{uuid}", Description: "Delete infra provider by uuid"},
	{Resource: "infra-billing", Slug: "create-bill-record", Kind: "write", Method: "POST", Path: "/api/infra-billing/history", Description: "Create infra billing history"},
	{Resource: "infra-billing", Slug: "list-bill-records", Kind: "read", Method: "GET", Path: "/api/infra-billing/history", Description: "Get infra billing history"},
	{Resource: "infra-billing", Slug: "delete-bill-record", Kind: "write", Method: "DELETE", Path: "/api/infra-billing/history/{uuid}", Description: "Delete infra billing history"},
	{Resource: "infra-billing", Slug: "list-billing-nodes", Kind: "read", Method: "GET", Path: "/api/infra-billing/nodes", Description: "Get infra billing nodes"},
	{Resource: "infra-billing", Slug: "update-billing-node", Kind: "write", Method: "PATCH", Path: "/api/infra-billing/nodes", Description: "Update infra billing nodes"},
	{Resource: "infra-billing", Slug: "create-billing-node", Kind: "write", Method: "POST", Path: "/api/infra-billing/nodes", Description: "Create infra billing node"},
	{Resource: "infra-billing", Slug: "delete-billing-node", Kind: "write", Method: "DELETE", Path: "/api/infra-billing/nodes/{uuid}", Description: "Delete infra billing node"},
	{Resource: "bandwidth-stats", Slug: "internal-squad-usage", Kind: "read", Method: "GET", Path: "/api/bandwidth-stats/internal-squads/{uuid}/usage", Description: "Get internal squad users traffic usage for a period"},
	{Resource: "bandwidth-stats", Slug: "get-a-single-user-daily-traffic-usage-on-the-internal-squad-nodes-for-a-period", Kind: "read", Method: "GET", Path: "/api/bandwidth-stats/internal-squads/{squadUuid}/users/{userId}/usage", Description: "Get a single user daily traffic usage on the internal squad nodes for a period"},
	{Resource: "bandwidth-stats", Slug: "node-usage", Kind: "read", Method: "POST", Path: "/api/bandwidth-stats/nodes/usage", Description: "Get users exceeding a traffic threshold on the given nodes for a period"},
	{Resource: "bandwidth-stats", Slug: "node-users-usage", Kind: "read", Method: "GET", Path: "/api/bandwidth-stats/nodes/{uuid}/users", Description: "Get Node Users Usage by Node UUID"},
	{Resource: "bandwidth-stats", Slug: "nodes-users-usage", Kind: "read", Method: "POST", Path: "/api/bandwidth-stats/nodes/users", Description: "Get Nodes Users Usage by Nodes UUIDs"},
	{Resource: "bandwidth-stats", Slug: "user-usage", Kind: "read", Method: "GET", Path: "/api/bandwidth-stats/users/{userId}", Description: "Get User Usage by Range"},
	{Resource: "bandwidth-stats", Slug: "nodes-usage", Kind: "read", Method: "GET", Path: "/api/bandwidth-stats/nodes", Description: "Get Nodes Usage by Range"},
	{Resource: "internal-squads", Slug: "list-tags", Kind: "read", Method: "GET", Path: "/api/internal-squads/tags", Description: "Get tags of Internal Squads"},
	{Resource: "internal-squads", Slug: "set-tags", Kind: "write", Method: "PATCH", Path: "/api/internal-squads/tags", Description: "Set tags of Internal Squad"},
	{Resource: "internal-squads", Slug: "list", Kind: "read", Method: "GET", Path: "/api/internal-squads", Description: "Get all internal squads"},
	{Resource: "internal-squads", Slug: "create", Kind: "write", Method: "POST", Path: "/api/internal-squads", Description: "Create internal squad"},
	{Resource: "internal-squads", Slug: "update", Kind: "write", Method: "PATCH", Path: "/api/internal-squads", Description: "Update internal squad"},
	{Resource: "internal-squads", Slug: "get", Kind: "read", Method: "GET", Path: "/api/internal-squads/{uuid}", Description: "Get internal squad by uuid"},
	{Resource: "internal-squads", Slug: "delete", Kind: "write", Method: "DELETE", Path: "/api/internal-squads/{uuid}", Description: "Delete internal squad"},
	{Resource: "internal-squads", Slug: "accessible-nodes", Kind: "read", Method: "GET", Path: "/api/internal-squads/{uuid}/accessible-nodes", Description: "Get internal squad accessible nodes"},
	{Resource: "internal-squads", Slug: "internal-squad-usage", Kind: "read", Method: "GET", Path: "/api/internal-squads/{uuid}/usage", Description: "Get internal squad users traffic usage for a period"},
	{Resource: "internal-squads", Slug: "add-users", Kind: "write", Method: "POST", Path: "/api/internal-squads/{uuid}/bulk-actions/add-users", Description: "Add all users to internal squad"},
	{Resource: "internal-squads", Slug: "remove-users", Kind: "write", Method: "DELETE", Path: "/api/internal-squads/{uuid}/bulk-actions/remove-users", Description: "Delete users from internal squad"},
	{Resource: "internal-squads", Slug: "reorder", Kind: "write", Method: "POST", Path: "/api/internal-squads/actions/reorder", Description: "Reorder internal squads"},
	{Resource: "internal-squads", Slug: "add-many-users", Kind: "write", Method: "POST", Path: "/api/internal-squads/{uuid}/bulk-actions/add-many-users", Description: "Add many users to internal squad"},
	{Resource: "internal-squads", Slug: "remove-many-users", Kind: "write", Method: "DELETE", Path: "/api/internal-squads/{uuid}/bulk-actions/remove-many-users", Description: "Delete many users from internal squad"},
	{Resource: "keygen", Slug: "get", Kind: "read", Method: "GET", Path: "/api/keygen", Description: "Get SECRET_KEY for Exodus Node"},
	{Resource: "metadata", Slug: "get-user", Kind: "read", Method: "GET", Path: "/api/metadata/user/{userId}", Description: "Get user metadata"},
	{Resource: "metadata", Slug: "upsert-user", Kind: "write", Method: "PUT", Path: "/api/metadata/user/{userId}", Description: "Update or create User Metadata"},
	{Resource: "metadata", Slug: "get-node", Kind: "read", Method: "GET", Path: "/api/metadata/node/{uuid}", Description: "Get node metadata"},
	{Resource: "metadata", Slug: "upsert-node", Kind: "write", Method: "PUT", Path: "/api/metadata/node/{uuid}", Description: "Update or create Node Metadata"},
	{Resource: "node-integrations", Slug: "list", Kind: "read", Method: "GET", Path: "/api/node-integrations", Description: "Get all Node Integrations"},
	{Resource: "node-integrations", Slug: "create", Kind: "write", Method: "POST", Path: "/api/node-integrations", Description: "Create Node Integration"},
	{Resource: "node-integrations", Slug: "update", Kind: "write", Method: "PATCH", Path: "/api/node-integrations", Description: "Update Node Integration"},
	{Resource: "node-integrations", Slug: "get", Kind: "read", Method: "GET", Path: "/api/node-integrations/{uuid}", Description: "Get Node Integration by uuid"},
	{Resource: "node-integrations", Slug: "delete", Kind: "write", Method: "DELETE", Path: "/api/node-integrations/{uuid}", Description: "Delete Node Integration"},
	{Resource: "node-plugins", Slug: "torrent-blocker-reports", Kind: "read", Method: "GET", Path: "/api/node-plugins/torrent-blocker", Description: "Get Torrent Blocker Reports"},
	{Resource: "node-plugins", Slug: "torrent-blocker-stats", Kind: "read", Method: "GET", Path: "/api/node-plugins/torrent-blocker/stats", Description: "Get Torrent Blocker Reports Stats"},
	{Resource: "node-plugins", Slug: "truncate", Kind: "write", Method: "DELETE", Path: "/api/node-plugins/torrent-blocker/truncate", Description: "Truncate Torrent Blocker Reports"},
	{Resource: "node-plugins", Slug: "list-tags", Kind: "read", Method: "GET", Path: "/api/node-plugins/tags", Description: "Get tags of Node Plugins"},
	{Resource: "node-plugins", Slug: "set-tags", Kind: "write", Method: "PATCH", Path: "/api/node-plugins/tags", Description: "Set tags of Node Plugin"},
	{Resource: "node-plugins", Slug: "shared-lists-list", Kind: "read", Method: "GET", Path: "/api/node-plugins/shared-lists", Description: "Get Shared Lists (Preview)"},
	{Resource: "node-plugins", Slug: "shared-lists-create", Kind: "write", Method: "POST", Path: "/api/node-plugins/shared-lists", Description: "Create Shared List"},
	{Resource: "node-plugins", Slug: "shared-lists-update", Kind: "write", Method: "PATCH", Path: "/api/node-plugins/shared-lists", Description: "Update Shared List"},
	{Resource: "node-plugins", Slug: "shared-lists-delete", Kind: "write", Method: "DELETE", Path: "/api/node-plugins/shared-lists", Description: "Delete Shared List by name"},
	{Resource: "node-plugins", Slug: "shared-lists-get", Kind: "read", Method: "GET", Path: "/api/node-plugins/shared-lists/by-name", Description: "Get Shared List by name"},
	{Resource: "node-plugins", Slug: "shared-lists-sync", Kind: "write", Method: "POST", Path: "/api/node-plugins/shared-lists/actions/sync", Description: "Sync Shared List to nodes"},
	{Resource: "node-plugins", Slug: "list", Kind: "read", Method: "GET", Path: "/api/node-plugins", Description: "Get all Node Plugins"},
	{Resource: "node-plugins", Slug: "update", Kind: "write", Method: "PATCH", Path: "/api/node-plugins", Description: "Update Node Plugin"},
	{Resource: "node-plugins", Slug: "create", Kind: "write", Method: "POST", Path: "/api/node-plugins", Description: "Create Node Plugin"},
	{Resource: "node-plugins", Slug: "get", Kind: "read", Method: "GET", Path: "/api/node-plugins/{uuid}", Description: "Get Node Plugin by uuid"},
	{Resource: "node-plugins", Slug: "delete", Kind: "write", Method: "DELETE", Path: "/api/node-plugins/{uuid}", Description: "Delete Node Plugin"},
	{Resource: "node-plugins", Slug: "reorder", Kind: "write", Method: "POST", Path: "/api/node-plugins/actions/reorder", Description: "Reorder Node Plugins"},
	{Resource: "node-plugins", Slug: "clone", Kind: "write", Method: "POST", Path: "/api/node-plugins/actions/clone", Description: "Clone Node Plugin"},
	{Resource: "node-plugins", Slug: "sync", Kind: "write", Method: "POST", Path: "/api/node-plugins/actions/sync", Description: "Sync Node Plugin to nodes"},
	{Resource: "node-plugins", Slug: "executor", Kind: "write", Method: "POST", Path: "/api/node-plugins/executor", Description: "Execute command on node plugins"},
	{Resource: "nodes", Slug: "list-tags", Kind: "read", Method: "GET", Path: "/api/nodes/tags", Description: "Get nodes tags"},
	{Resource: "nodes", Slug: "create", Kind: "write", Method: "POST", Path: "/api/nodes", Description: "Create a new node"},
	{Resource: "nodes", Slug: "list", Kind: "read", Method: "GET", Path: "/api/nodes", Description: "Get nodes"},
	{Resource: "nodes", Slug: "update", Kind: "write", Method: "PATCH", Path: "/api/nodes", Description: "Update node"},
	{Resource: "nodes", Slug: "get", Kind: "read", Method: "GET", Path: "/api/nodes/{uuid}", Description: "Get node by UUID"},
	{Resource: "nodes", Slug: "delete", Kind: "write", Method: "DELETE", Path: "/api/nodes/{uuid}", Description: "Delete a node"},
	{Resource: "nodes", Slug: "enable", Kind: "write", Method: "POST", Path: "/api/nodes/{uuid}/actions/enable", Description: "Enable a node"},
	{Resource: "nodes", Slug: "disable", Kind: "write", Method: "POST", Path: "/api/nodes/{uuid}/actions/disable", Description: "Disable a node"},
	{Resource: "nodes", Slug: "restart", Kind: "write", Method: "POST", Path: "/api/nodes/{uuid}/actions/restart", Description: "Restart node"},
	{Resource: "nodes", Slug: "reset-traffic", Kind: "write", Method: "POST", Path: "/api/nodes/{uuid}/actions/reset-traffic", Description: "Reset Node Traffic"},
	{Resource: "nodes", Slug: "restart-all", Kind: "write", Method: "POST", Path: "/api/nodes/actions/restart-all", Description: "Restart all nodes"},
	{Resource: "nodes", Slug: "reorder", Kind: "write", Method: "POST", Path: "/api/nodes/actions/reorder", Description: "Reorder nodes"},
	{Resource: "nodes", Slug: "bulk-profile-modification", Kind: "write", Method: "POST", Path: "/api/nodes/bulk-actions/profile-modification", Description: "Modify Inbounds & Profile for many nodes"},
	{Resource: "nodes", Slug: "bulk-actions", Kind: "write", Method: "POST", Path: "/api/nodes/bulk-actions", Description: "Perform actions for many nodes"},
	{Resource: "nodes", Slug: "bulk-update", Kind: "write", Method: "POST", Path: "/api/nodes/bulk-actions/update", Description: "Update many nodes"},
	{Resource: "subscription-page-configs", Slug: "list-tags", Kind: "read", Method: "GET", Path: "/api/subscription-page-configs/tags", Description: "Get tags of Subpage Configs"},
	{Resource: "subscription-page-configs", Slug: "set-tags", Kind: "write", Method: "PATCH", Path: "/api/subscription-page-configs/tags", Description: "Set tags of Subpage Config"},
	{Resource: "subscription-page-configs", Slug: "list", Kind: "read", Method: "GET", Path: "/api/subscription-page-configs", Description: "Get all subscription page configs"},
	{Resource: "subscription-page-configs", Slug: "update", Kind: "write", Method: "PATCH", Path: "/api/subscription-page-configs", Description: "Update subscription page config"},
	{Resource: "subscription-page-configs", Slug: "create", Kind: "write", Method: "POST", Path: "/api/subscription-page-configs", Description: "Create subscription page config"},
	{Resource: "subscription-page-configs", Slug: "get", Kind: "read", Method: "GET", Path: "/api/subscription-page-configs/{uuid}", Description: "Get subscription page config by uuid"},
	{Resource: "subscription-page-configs", Slug: "delete", Kind: "write", Method: "DELETE", Path: "/api/subscription-page-configs/{uuid}", Description: "Delete subscription page config"},
	{Resource: "subscription-page-configs", Slug: "reorder", Kind: "write", Method: "POST", Path: "/api/subscription-page-configs/actions/reorder", Description: "Reorder subscription page configs"},
	{Resource: "subscription-page-configs", Slug: "clone", Kind: "write", Method: "POST", Path: "/api/subscription-page-configs/actions/clone", Description: "Clone subscription page config"},
	{Resource: "subscription-settings", Slug: "get", Kind: "read", Method: "GET", Path: "/api/subscription-settings", Description: "Get subscription settings"},
	{Resource: "subscription-settings", Slug: "update", Kind: "write", Method: "PATCH", Path: "/api/subscription-settings", Description: "Update subscription settings"},
	{Resource: "subscription-template", Slug: "list-tags", Kind: "read", Method: "GET", Path: "/api/subscription-templates/tags", Description: "Get tags of Subscription Templates"},
	{Resource: "subscription-template", Slug: "set-tags", Kind: "write", Method: "PATCH", Path: "/api/subscription-templates/tags", Description: "Set tags of Subscription Template"},
	{Resource: "subscription-template", Slug: "list", Kind: "read", Method: "GET", Path: "/api/subscription-templates", Description: "Get all subscription templates (wihout content)"},
	{Resource: "subscription-template", Slug: "update", Kind: "write", Method: "PATCH", Path: "/api/subscription-templates", Description: "Update subscription template"},
	{Resource: "subscription-template", Slug: "create", Kind: "write", Method: "POST", Path: "/api/subscription-templates", Description: "Create subscription template"},
	{Resource: "subscription-template", Slug: "get", Kind: "read", Method: "GET", Path: "/api/subscription-templates/{uuid}", Description: "Get subscription template by uuid"},
	{Resource: "subscription-template", Slug: "delete", Kind: "write", Method: "DELETE", Path: "/api/subscription-templates/{uuid}", Description: "Delete subscription template"},
	{Resource: "subscription-template", Slug: "reorder", Kind: "write", Method: "POST", Path: "/api/subscription-templates/actions/reorder", Description: "Reorder subscription templates"},
	{Resource: "subscriptions", Slug: "list", Kind: "read", Method: "GET", Path: "/api/subscriptions", Description: "Get all subscriptions"},
	{Resource: "subscriptions", Slug: "by-username", Kind: "read", Method: "GET", Path: "/api/subscriptions/by-username/{username}", Description: "Get subscription by username"},
	{Resource: "subscriptions", Slug: "by-short-uuid-protected", Kind: "read", Method: "GET", Path: "/api/subscriptions/by-short-uuid/{shortUuid}", Description: "Get subscription by short uuid (protected route)"},
	{Resource: "subscriptions", Slug: "by-id", Kind: "read", Method: "GET", Path: "/api/subscriptions/by-id/{userId}", Description: "Get subscription by User ID"},
	{Resource: "subscriptions", Slug: "raw", Kind: "read", Method: "GET", Path: "/api/subscriptions/by-short-uuid/{shortUuid}/raw", Description: "Get Raw Subscription by Short UUID"},
	{Resource: "subscriptions", Slug: "subpage-config", Kind: "read", Method: "GET", Path: "/api/subscriptions/subpage-config/{shortUuid}", Description: "Get Subpage Config by Short UUID"},
	{Resource: "subscriptions", Slug: "connection-keys", Kind: "read", Method: "GET", Path: "/api/subscriptions/connection-keys/{userId}", Description: "Get connection keys (base64 format) by user id"},
	{Resource: "system", Slug: "metadata", Kind: "read", Method: "GET", Path: "/api/system/metadata", Description: "Get Exodus Information"},
	{Resource: "system", Slug: "configuration", Kind: "read", Method: "GET", Path: "/api/system/configuration", Description: "Get Exodus Configuration"},
	{Resource: "system", Slug: "stats", Kind: "read", Method: "GET", Path: "/api/system/stats", Description: "Get Stats"},
	{Resource: "system", Slug: "bandwidth-stats", Kind: "read", Method: "GET", Path: "/api/system/stats/bandwidth", Description: "Get Bandwidth Stats"},
	{Resource: "system", Slug: "nodes-statistics", Kind: "read", Method: "GET", Path: "/api/system/stats/nodes", Description: "Get Nodes Statistics"},
	{Resource: "system", Slug: "exodus-health", Kind: "read", Method: "GET", Path: "/api/system/health", Description: "Get Exodus Health"},
	{Resource: "system", Slug: "nodes-metrics", Kind: "read", Method: "GET", Path: "/api/system/nodes/metrics", Description: "Get Nodes Metrics"},
	{Resource: "system", Slug: "generate-x25519", Kind: "read", Method: "GET", Path: "/api/system/tools/x25519/generate", Description: "Generate 30 X25519 keypairs"},
	{Resource: "system", Slug: "test-srr-matcher", Kind: "write", Method: "POST", Path: "/api/system/testers/srr-matcher", Description: "Test SRR Matcher"},
	{Resource: "system", Slug: "recap", Kind: "read", Method: "GET", Path: "/api/system/stats/recap", Description: "Get Recap"},
	{Resource: "system", Slug: "digest", Kind: "read", Method: "GET", Path: "/api/system/stats/digest", Description: "Get Stats Digest"},
	{Resource: "system", Slug: "http", Kind: "read", Method: "GET", Path: "/api/system/stats/http", Description: "Get HTTP Stats"},
	{Resource: "subscription-request-history", Slug: "list", Kind: "read", Method: "GET", Path: "/api/subscription-request-history", Description: "Get all subscription request history"},
	{Resource: "subscription-request-history", Slug: "stats", Kind: "read", Method: "GET", Path: "/api/subscription-request-history/stats", Description: "Get subscription request history stats"},
	{Resource: "users", Slug: "create", Kind: "write", Method: "POST", Path: "/api/users", Description: "Create a new user"},
	{Resource: "users", Slug: "update", Kind: "write", Method: "PATCH", Path: "/api/users", Description: "Update a user"},
	{Resource: "users", Slug: "list", Kind: "read", Method: "GET", Path: "/api/users", Description: "Get all users using offset-based pagination"},
	{Resource: "users", Slug: "delete", Kind: "write", Method: "DELETE", Path: "/api/users/{userId}", Description: "Delete user"},
	{Resource: "users", Slug: "by-id", Kind: "read", Method: "GET", Path: "/api/users/{userId}", Description: "Get user by ID"},
	{Resource: "users", Slug: "stream", Kind: "read", Method: "GET", Path: "/api/users/stream", Description: "Get all users using cursor-based (keyset) pagination with filtering options"},
	{Resource: "users", Slug: "list-tags", Kind: "read", Method: "GET", Path: "/api/users/tags", Description: "Get users tags"},
	{Resource: "users", Slug: "accessible-nodes", Kind: "read", Method: "GET", Path: "/api/users/{userId}/accessible-nodes", Description: "Get user accessible nodes"},
	{Resource: "users", Slug: "subscription-request-history", Kind: "read", Method: "GET", Path: "/api/users/{userId}/subscription-request-history", Description: "Get user subscription request history, recent 24 records"},
	{Resource: "users", Slug: "by-short-uuid", Kind: "read", Method: "GET", Path: "/api/users/by-short-uuid/{shortUuid}", Description: "Get user by Short UUID"},
	{Resource: "users", Slug: "by-username", Kind: "read", Method: "GET", Path: "/api/users/by-username/{username}", Description: "Get user by username"},
	{Resource: "users", Slug: "revoke-subscription", Kind: "write", Method: "POST", Path: "/api/users/{userId}/actions/revoke", Description: "Revoke user subscription"},
	{Resource: "users", Slug: "disable", Kind: "write", Method: "POST", Path: "/api/users/{userId}/actions/disable", Description: "Disable user"},
	{Resource: "users", Slug: "enable", Kind: "write", Method: "POST", Path: "/api/users/{userId}/actions/enable", Description: "Enable user"},
	{Resource: "users", Slug: "reset-traffic", Kind: "write", Method: "POST", Path: "/api/users/{userId}/actions/reset-traffic", Description: "Reset user traffic"},
	{Resource: "users", Slug: "extend", Kind: "write", Method: "POST", Path: "/api/users/{userId}/actions/extend", Description: "Extend user expiration date"},
	{Resource: "users", Slug: "resolve", Kind: "read", Method: "POST", Path: "/api/users/resolve", Description: "Resolve a user"},
	{Resource: "users", Slug: "bulk-delete-by-status", Kind: "write", Method: "POST", Path: "/api/users/bulk/delete-by-status", Description: "Bulk delete users by status"},
	{Resource: "users", Slug: "bulk-delete", Kind: "write", Method: "POST", Path: "/api/users/bulk/delete", Description: "Bulk delete users by User IDs"},
	{Resource: "users", Slug: "bulk-revoke-subscription", Kind: "write", Method: "POST", Path: "/api/users/bulk/revoke-subscription", Description: "Revoke users subscription by User IDs"},
	{Resource: "users", Slug: "bulk-reset-traffic", Kind: "write", Method: "POST", Path: "/api/users/bulk/reset-traffic", Description: "Bulk reset traffic users by User IDs"},
	{Resource: "users", Slug: "bulk-update-users", Kind: "write", Method: "POST", Path: "/api/users/bulk/update", Description: "Bulk update users by User IDs"},
	{Resource: "users", Slug: "bulk-update-squads", Kind: "write", Method: "POST", Path: "/api/users/bulk/update-squads", Description: "Bulk update users internal squads by User IDs"},
	{Resource: "users", Slug: "bulk-extend-expiration-date", Kind: "write", Method: "POST", Path: "/api/users/bulk/extend-expiration-date", Description: "Extend expiration date for specified users by days"},
	{Resource: "users", Slug: "bulk-all-update-users", Kind: "write", Method: "POST", Path: "/api/users/bulk/all/update", Description: "Bulk update all users"},
	{Resource: "users", Slug: "bulk-all-reset-traffic", Kind: "write", Method: "POST", Path: "/api/users/bulk/all/reset-traffic", Description: "Reset user used traffic for all users"},
	{Resource: "users", Slug: "bulk-all-extend-expiration-date", Kind: "write", Method: "POST", Path: "/api/users/bulk/all/extend-expiration-date", Description: "Extend expiration date for all users by days"},
}
