// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: node.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Stat represents a single statistic entry.
type Stat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stat) Reset() {
	*x = Stat{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stat) ProtoMessage() {}

func (x *Stat) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stat.ProtoReflect.Descriptor instead.
func (*Stat) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *Stat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stat) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// GetApiStatsRequest is the request message for GetApiStats.
type GetApiStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiStatsRequest) Reset() {
	*x = GetApiStatsRequest{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiStatsRequest) ProtoMessage() {}

func (x *GetApiStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiStatsRequest.ProtoReflect.Descriptor instead.
func (*GetApiStatsRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

// GetApiStatsResponse is the response message for GetApiStats.
type GetApiStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*Stat                `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiStatsResponse) Reset() {
	*x = GetApiStatsResponse{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiStatsResponse) ProtoMessage() {}

func (x *GetApiStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiStatsResponse.ProtoReflect.Descriptor instead.
func (*GetApiStatsResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

func (x *GetApiStatsResponse) GetStats() []*Stat {
	if x != nil {
		return x.Stats
	}
	return nil
}

// GetLogDataRequest is the request message for GetLogData.
type GetLogDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogDataRequest) Reset() {
	*x = GetLogDataRequest{}
	mi := &file_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogDataRequest) ProtoMessage() {}

func (x *GetLogDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogDataRequest.ProtoReflect.Descriptor instead.
func (*GetLogDataRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{3}
}

// UserLogData contains log data for a specific user.
type UserLogData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ValidIps      []string               `protobuf:"bytes,1,rep,name=valid_ips,json=validIps,proto3" json:"valid_ips,omitempty"`
	DnsStats      map[string]int32       `protobuf:"bytes,2,rep,name=dns_stats,json=dnsStats,proto3" json:"dns_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLogData) Reset() {
	*x = UserLogData{}
	mi := &file_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLogData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogData) ProtoMessage() {}

func (x *UserLogData) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogData.ProtoReflect.Descriptor instead.
func (*UserLogData) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{4}
}

func (x *UserLogData) GetValidIps() []string {
	if x != nil {
		return x.ValidIps
	}
	return nil
}

func (x *UserLogData) GetDnsStats() map[string]int32 {
	if x != nil {
		return x.DnsStats
	}
	return nil
}

// GetLogDataResponse is the response message for GetLogData.
type GetLogDataResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	UserLogData   map[string]*UserLogData `protobuf:"bytes,1,rep,name=user_log_data,json=userLogData,proto3" json:"user_log_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogDataResponse) Reset() {
	*x = GetLogDataResponse{}
	mi := &file_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogDataResponse) ProtoMessage() {}

func (x *GetLogDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogDataResponse.ProtoReflect.Descriptor instead.
func (*GetLogDataResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{5}
}

func (x *GetLogDataResponse) GetUserLogData() map[string]*UserLogData {
	if x != nil {
		return x.UserLogData
	}
	return nil
}

// IdInbound represents an inbound configuration for a user.
type IdInbound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InboundTag    string                 `protobuf:"bytes,2,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdInbound) Reset() {
	*x = IdInbound{}
	mi := &file_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdInbound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdInbound) ProtoMessage() {}

func (x *IdInbound) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdInbound.ProtoReflect.Descriptor instead.
func (*IdInbound) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{6}
}

func (x *IdInbound) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IdInbound) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

// User represents a user configuration.
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	IdInbounds    []*IdInbound           `protobuf:"bytes,2,rep,name=id_inbounds,json=idInbounds,proto3" json:"id_inbounds,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{7}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetIdInbounds() []*IdInbound {
	if x != nil {
		return x.IdInbounds
	}
	return nil
}

func (x *User) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// ListUsersRequest is the request message for ListUsers.
type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{8}
}

// ListUsersResponse is the response message for ListUsers.
type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{9}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

// StreamConfig defines the configuration for streaming.
type StreamConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IntervalSeconds int32                  `protobuf:"varint,1,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamConfig) Reset() {
	*x = StreamConfig{}
	mi := &file_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamConfig) ProtoMessage() {}

func (x *StreamConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamConfig.ProtoReflect.Descriptor instead.
func (*StreamConfig) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{10}
}

func (x *StreamConfig) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

// NodeDataRequest is the request message for StreamNodeData.
type NodeDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*NodeDataRequest_Config
	//	*NodeDataRequest_ListUsers
	Request       isNodeDataRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeDataRequest) Reset() {
	*x = NodeDataRequest{}
	mi := &file_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDataRequest) ProtoMessage() {}

func (x *NodeDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDataRequest.ProtoReflect.Descriptor instead.
func (*NodeDataRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{11}
}

func (x *NodeDataRequest) GetRequest() isNodeDataRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *NodeDataRequest) GetConfig() *StreamConfig {
	if x != nil {
		if x, ok := x.Request.(*NodeDataRequest_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *NodeDataRequest) GetListUsers() *ListUsersRequest {
	if x != nil {
		if x, ok := x.Request.(*NodeDataRequest_ListUsers); ok {
			return x.ListUsers
		}
	}
	return nil
}

type isNodeDataRequest_Request interface {
	isNodeDataRequest_Request()
}

type NodeDataRequest_Config struct {
	Config *StreamConfig `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type NodeDataRequest_ListUsers struct {
	ListUsers *ListUsersRequest `protobuf:"bytes,2,opt,name=list_users,json=listUsers,proto3,oneof"`
}

func (*NodeDataRequest_Config) isNodeDataRequest_Request() {}

func (*NodeDataRequest_ListUsers) isNodeDataRequest_Request() {}

// NodeDataResponse is the response message for StreamNodeData.
type NodeDataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*NodeDataResponse_Stats
	//	*NodeDataResponse_Users
	//	*NodeDataResponse_LogData
	Response      isNodeDataResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeDataResponse) Reset() {
	*x = NodeDataResponse{}
	mi := &file_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDataResponse) ProtoMessage() {}

func (x *NodeDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDataResponse.ProtoReflect.Descriptor instead.
func (*NodeDataResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{12}
}

func (x *NodeDataResponse) GetResponse() isNodeDataResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *NodeDataResponse) GetStats() *GetApiStatsResponse {
	if x != nil {
		if x, ok := x.Response.(*NodeDataResponse_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

func (x *NodeDataResponse) GetUsers() *ListUsersResponse {
	if x != nil {
		if x, ok := x.Response.(*NodeDataResponse_Users); ok {
			return x.Users
		}
	}
	return nil
}

func (x *NodeDataResponse) GetLogData() *GetLogDataResponse {
	if x != nil {
		if x, ok := x.Response.(*NodeDataResponse_LogData); ok {
			return x.LogData
		}
	}
	return nil
}

type isNodeDataResponse_Response interface {
	isNodeDataResponse_Response()
}

type NodeDataResponse_Stats struct {
	Stats *GetApiStatsResponse `protobuf:"bytes,1,opt,name=stats,proto3,oneof"`
}

type NodeDataResponse_Users struct {
	Users *ListUsersResponse `protobuf:"bytes,2,opt,name=users,proto3,oneof"`
}

type NodeDataResponse_LogData struct {
	LogData *GetLogDataResponse `protobuf:"bytes,3,opt,name=log_data,json=logData,proto3,oneof"`
}

func (*NodeDataResponse_Stats) isNodeDataResponse_Response() {}

func (*NodeDataResponse_Users) isNodeDataResponse_Response() {}

func (*NodeDataResponse_LogData) isNodeDataResponse_Response() {}

// AddUsersRequest specifies one or more users to add to the node.
type AddUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usernames     []string               `protobuf:"bytes,1,rep,name=usernames,proto3" json:"usernames,omitempty"`
	InboundTag    string                 `protobuf:"bytes,2,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUsersRequest) Reset() {
	*x = AddUsersRequest{}
	mi := &file_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUsersRequest) ProtoMessage() {}

func (x *AddUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUsersRequest.ProtoReflect.Descriptor instead.
func (*AddUsersRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{13}
}

func (x *AddUsersRequest) GetUsernames() []string {
	if x != nil {
		return x.Usernames
	}
	return nil
}

func (x *AddUsersRequest) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

// DeleteUsersRequest specifies one or more users to delete from the node.
type DeleteUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usernames     []string               `protobuf:"bytes,1,rep,name=usernames,proto3" json:"usernames,omitempty"`
	InboundTag    string                 `protobuf:"bytes,2,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUsersRequest) Reset() {
	*x = DeleteUsersRequest{}
	mi := &file_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUsersRequest) ProtoMessage() {}

func (x *DeleteUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUsersRequest.ProtoReflect.Descriptor instead.
func (*DeleteUsersRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteUsersRequest) GetUsernames() []string {
	if x != nil {
		return x.Usernames
	}
	return nil
}

func (x *DeleteUsersRequest) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

// SetUserEnabledRequest specifies one or more users to enable or disable.
type SetUserEnabledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usernames     []string               `protobuf:"bytes,1,rep,name=usernames,proto3" json:"usernames,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserEnabledRequest) Reset() {
	*x = SetUserEnabledRequest{}
	mi := &file_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserEnabledRequest) ProtoMessage() {}

func (x *SetUserEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserEnabledRequest.ProtoReflect.Descriptor instead.
func (*SetUserEnabledRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{15}
}

func (x *SetUserEnabledRequest) GetUsernames() []string {
	if x != nil {
		return x.Usernames
	}
	return nil
}

func (x *SetUserEnabledRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// OperationResponse represents the result of an operation.
type OperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *status.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Usernames     []string               `protobuf:"bytes,2,rep,name=usernames,proto3" json:"usernames,omitempty"`
	Users         *ListUsersResponse     `protobuf:"bytes,3,opt,name=users,proto3" json:"users,omitempty"`
	Credentials   map[string]string      `protobuf:"bytes,4,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{16}
}

func (x *OperationResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *OperationResponse) GetUsernames() []string {
	if x != nil {
		return x.Usernames
	}
	return nil
}

func (x *OperationResponse) GetUsers() *ListUsersResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *OperationResponse) GetCredentials() map[string]string {
	if x != nil {
		return x.Credentials
	}
	return nil
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12\x05proto\x1a\x17google/rpc/status.proto\"0\n" +
	"\x04Stat\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x14\n" +
	"\x12GetApiStatsRequest\"8\n" +
	"\x13GetApiStatsResponse\x12!\n" +
	"\x05stats\x18\x01 \x03(\v2\v.proto.StatR\x05stats\"\x13\n" +
	"\x11GetLogDataRequest\"\xa6\x01\n" +
	"\vUserLogData\x12\x1b\n" +
	"\tvalid_ips\x18\x01 \x03(\tR\bvalidIps\x12=\n" +
	"\tdns_stats\x18\x02 \x03(\v2 .proto.UserLogData.DnsStatsEntryR\bdnsStats\x1a;\n" +
	"\rDnsStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xb8\x01\n" +
	"\x12GetLogDataResponse\x12N\n" +
	"\ruser_log_data\x18\x01 \x03(\v2*.proto.GetLogDataResponse.UserLogDataEntryR\vuserLogData\x1aR\n" +
	"\x10UserLogDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.proto.UserLogDataR\x05value:\x028\x01\"<\n" +
	"\tIdInbound\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vinbound_tag\x18\x02 \x01(\tR\n" +
	"inboundTag\"o\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x121\n" +
	"\vid_inbounds\x18\x02 \x03(\v2\x10.proto.IdInboundR\n" +
	"idInbounds\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\"\x12\n" +
	"\x10ListUsersRequest\"6\n" +
	"\x11ListUsersResponse\x12!\n" +
	"\x05users\x18\x01 \x03(\v2\v.proto.UserR\x05users\"9\n" +
	"\fStreamConfig\x12)\n" +
	"\x10interval_seconds\x18\x01 \x01(\x05R\x0fintervalSeconds\"\x85\x01\n" +
	"\x0fNodeDataRequest\x12-\n" +
	"\x06config\x18\x01 \x01(\v2\x13.proto.StreamConfigH\x00R\x06config\x128\n" +
	"\n" +
	"list_users\x18\x02 \x01(\v2\x17.proto.ListUsersRequestH\x00R\tlistUsersB\t\n" +
	"\arequest\"\xbc\x01\n" +
	"\x10NodeDataResponse\x122\n" +
	"\x05stats\x18\x01 \x01(\v2\x1a.proto.GetApiStatsResponseH\x00R\x05stats\x120\n" +
	"\x05users\x18\x02 \x01(\v2\x18.proto.ListUsersResponseH\x00R\x05users\x126\n" +
	"\blog_data\x18\x03 \x01(\v2\x19.proto.GetLogDataResponseH\x00R\alogDataB\n" +
	"\n" +
	"\bresponse\"P\n" +
	"\x0fAddUsersRequest\x12\x1c\n" +
	"\tusernames\x18\x01 \x03(\tR\tusernames\x12\x1f\n" +
	"\vinbound_tag\x18\x02 \x01(\tR\n" +
	"inboundTag\"S\n" +
	"\x12DeleteUsersRequest\x12\x1c\n" +
	"\tusernames\x18\x01 \x03(\tR\tusernames\x12\x1f\n" +
	"\vinbound_tag\x18\x02 \x01(\tR\n" +
	"inboundTag\"O\n" +
	"\x15SetUserEnabledRequest\x12\x1c\n" +
	"\tusernames\x18\x01 \x03(\tR\tusernames\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"\x9a\x02\n" +
	"\x11OperationResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06status\x12\x1c\n" +
	"\tusernames\x18\x02 \x03(\tR\tusernames\x12.\n" +
	"\x05users\x18\x03 \x01(\v2\x18.proto.ListUsersResponseR\x05users\x12K\n" +
	"\vcredentials\x18\x04 \x03(\v2).proto.OperationResponse.CredentialsEntryR\vcredentials\x1a>\n" +
	"\x10CredentialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xf7\x03\n" +
	"\vNodeService\x12@\n" +
	"\tListUsers\x12\x17.proto.ListUsersRequest\x1a\x18.proto.ListUsersResponse\"\x00\x12F\n" +
	"\vGetApiStats\x12\x19.proto.GetApiStatsRequest\x1a\x1a.proto.GetApiStatsResponse\"\x00\x12C\n" +
	"\n" +
	"GetLogData\x12\x18.proto.GetLogDataRequest\x1a\x19.proto.GetLogDataResponse\"\x00\x12G\n" +
	"\x0eStreamNodeData\x12\x16.proto.NodeDataRequest\x1a\x17.proto.NodeDataResponse\"\x00(\x010\x01\x12>\n" +
	"\bAddUsers\x12\x16.proto.AddUsersRequest\x1a\x18.proto.OperationResponse\"\x00\x12D\n" +
	"\vDeleteUsers\x12\x19.proto.DeleteUsersRequest\x1a\x18.proto.OperationResponse\"\x00\x12J\n" +
	"\x0eSetUserEnabled\x12\x1c.proto.SetUserEnabledRequest\x1a\x18.proto.OperationResponse\"\x00B\x12Z\x10v2ray-stat/protob\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_node_proto_goTypes = []any{
	(*Stat)(nil),                  // 0: proto.Stat
	(*GetApiStatsRequest)(nil),    // 1: proto.GetApiStatsRequest
	(*GetApiStatsResponse)(nil),   // 2: proto.GetApiStatsResponse
	(*GetLogDataRequest)(nil),     // 3: proto.GetLogDataRequest
	(*UserLogData)(nil),           // 4: proto.UserLogData
	(*GetLogDataResponse)(nil),    // 5: proto.GetLogDataResponse
	(*IdInbound)(nil),             // 6: proto.IdInbound
	(*User)(nil),                  // 7: proto.User
	(*ListUsersRequest)(nil),      // 8: proto.ListUsersRequest
	(*ListUsersResponse)(nil),     // 9: proto.ListUsersResponse
	(*StreamConfig)(nil),          // 10: proto.StreamConfig
	(*NodeDataRequest)(nil),       // 11: proto.NodeDataRequest
	(*NodeDataResponse)(nil),      // 12: proto.NodeDataResponse
	(*AddUsersRequest)(nil),       // 13: proto.AddUsersRequest
	(*DeleteUsersRequest)(nil),    // 14: proto.DeleteUsersRequest
	(*SetUserEnabledRequest)(nil), // 15: proto.SetUserEnabledRequest
	(*OperationResponse)(nil),     // 16: proto.OperationResponse
	nil,                           // 17: proto.UserLogData.DnsStatsEntry
	nil,                           // 18: proto.GetLogDataResponse.UserLogDataEntry
	nil,                           // 19: proto.OperationResponse.CredentialsEntry
	(*status.Status)(nil),         // 20: google.rpc.Status
}
var file_node_proto_depIdxs = []int32{
	0,  // 0: proto.GetApiStatsResponse.stats:type_name -> proto.Stat
	17, // 1: proto.UserLogData.dns_stats:type_name -> proto.UserLogData.DnsStatsEntry
	18, // 2: proto.GetLogDataResponse.user_log_data:type_name -> proto.GetLogDataResponse.UserLogDataEntry
	6,  // 3: proto.User.id_inbounds:type_name -> proto.IdInbound
	7,  // 4: proto.ListUsersResponse.users:type_name -> proto.User
	10, // 5: proto.NodeDataRequest.config:type_name -> proto.StreamConfig
	8,  // 6: proto.NodeDataRequest.list_users:type_name -> proto.ListUsersRequest
	2,  // 7: proto.NodeDataResponse.stats:type_name -> proto.GetApiStatsResponse
	9,  // 8: proto.NodeDataResponse.users:type_name -> proto.ListUsersResponse
	5,  // 9: proto.NodeDataResponse.log_data:type_name -> proto.GetLogDataResponse
	20, // 10: proto.OperationResponse.status:type_name -> google.rpc.Status
	9,  // 11: proto.OperationResponse.users:type_name -> proto.ListUsersResponse
	19, // 12: proto.OperationResponse.credentials:type_name -> proto.OperationResponse.CredentialsEntry
	4,  // 13: proto.GetLogDataResponse.UserLogDataEntry.value:type_name -> proto.UserLogData
	8,  // 14: proto.NodeService.ListUsers:input_type -> proto.ListUsersRequest
	1,  // 15: proto.NodeService.GetApiStats:input_type -> proto.GetApiStatsRequest
	3,  // 16: proto.NodeService.GetLogData:input_type -> proto.GetLogDataRequest
	11, // 17: proto.NodeService.StreamNodeData:input_type -> proto.NodeDataRequest
	13, // 18: proto.NodeService.AddUsers:input_type -> proto.AddUsersRequest
	14, // 19: proto.NodeService.DeleteUsers:input_type -> proto.DeleteUsersRequest
	15, // 20: proto.NodeService.SetUserEnabled:input_type -> proto.SetUserEnabledRequest
	9,  // 21: proto.NodeService.ListUsers:output_type -> proto.ListUsersResponse
	2,  // 22: proto.NodeService.GetApiStats:output_type -> proto.GetApiStatsResponse
	5,  // 23: proto.NodeService.GetLogData:output_type -> proto.GetLogDataResponse
	12, // 24: proto.NodeService.StreamNodeData:output_type -> proto.NodeDataResponse
	16, // 25: proto.NodeService.AddUsers:output_type -> proto.OperationResponse
	16, // 26: proto.NodeService.DeleteUsers:output_type -> proto.OperationResponse
	16, // 27: proto.NodeService.SetUserEnabled:output_type -> proto.OperationResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	file_node_proto_msgTypes[11].OneofWrappers = []any{
		(*NodeDataRequest_Config)(nil),
		(*NodeDataRequest_ListUsers)(nil),
	}
	file_node_proto_msgTypes[12].OneofWrappers = []any{
		(*NodeDataResponse_Stats)(nil),
		(*NodeDataResponse_Users)(nil),
		(*NodeDataResponse_LogData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
